# Generated by Django 4.1 on 2023-07-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hs300Cne5BookToPrice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'hs300_cne5_book_to_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hs300Cne5EarningsYield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'hs300_cne5_earnings_yield',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hs300Cne5Growth',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'hs300_cne5_growth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hs300Cne5Leverage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'hs300_cne5_leverage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hs300Cne5NonLinearSize',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'hs300_cne5_non_linear_size',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hs300Cne5Size',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'hs300_cne5_size',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hs300Returns',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(unique=True)),
                ('value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'hs300_returns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hs300StockList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_code', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'db_table': 'hs300_stock_list',
                'managed': False,
            },
        ),
    ]
